#ifndef _CONFIG_H_
#define _CONFIG_H_

#define PI 3.14159265358979323846

#define VENTANA_ANCHO 1000
#define VENTANA_ALTO 800

#define JUEGO_FPS 100
#define JUEGO_COMBUSTIBLE_INICIAL 9999
#define JUEGO_COMBUSTIBLE_RADIANES 1
#define JUEGO_COMBUSTIBLE_POT_X_SEG 1

#define G 5

#define NAVE_ROTACION_PASO (PI/20)
#define NAVE_MAX_POTENCIA (3*G)

#define NAVE_X_INICIAL 100
#define NAVE_Y_INICIAL (VENTANA_ALTO-100)
#define NAVE_VX_INICIAL 100
#define NAVE_VY_INICIAL 0
#define NAVE_ANGULO_INICIAL (PI/2)
#define NAVE_POTENCIA_INICIAL 0

#endif // _CONFIG_H_

